### PR TITLE
Fix deleting a node in DAG to properly cleanup jsplumb instance

### LINKED ISSUE #24: Deleting a node with connections
I am using ReactDAG for creating a workflow management tool. 

Everytime I delete a node and pass the updated nodes and connections to reactDAG, the UI gets all messed up. I am not sure where am I going wrong. Any help would be greatly appreciated.

UI with nodes and connections
Screen Shot 2019-03-27 at 11 59 35 AM

UI after deleting notification node
Screen Shot 2019-03-27 at 12 00 02 PM

### PR DESCRIPTION
**Pull request by ajainarayanan**
Fixes: https://github.com/ajainarayanan/react-dag/issues/24

@mkm279 could you give it a review and try if this fixes your problem

### CODE REVIEW

**Comment by mkm279** [comment]
I will try it sometime later today and update you. The changes looks good though. It should fix it.

**Comment by mkm279** [comment]
I tried out your example. Working perfect. Was not able to make it work in my project, outgoing connections are not getting deleted. May be I have done something wrong while creating nodes. Looking into it. Feel free to merge it (y)

**Comment by mkm279** [comment]
Working. Thanks :)

**Comment by ajainarayanan** [comment]
Will merge and push a new version to npm tonight. Thanks for testing @mkm279!

**Pull request merged**
